### ISSUE TITLE
weex-vue-render升级到0.10的版本，显示就不正常了

### ISSUE THREAD

**Issue by hupanfeng** [weexteam/weex-picker#10]
有两个问题：

1. 样式变丑
2.实际选中的值和框住的值有偏差

![screenshot_2017-07-26-09-07-56](https://user-images.githubusercontent.com/4697988/28600065-375e0b40-71e2-11e7-8e07-1f4c65cf90af.png)

**Comment by hupanfeng** [comment]
作者实在是太懒了，提的问题都不回答。我自己解决了。
将picker.css 131行处的代码修改成如下的就可以了（需要自己重新编译）：
.weex-picker-body ul{
    display: block;
    width: 100%;
    -webkit-margin-before: 0px;
    -webkit-margin-after: 0px;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
    -webkit-padding-start: 0px;
}

**Comment by erha19** [comment]
Thank you for your report. fix #11
