### ISSUE TITLE
IOS 11中picker选择了一个选项后没有更新界

### ISSUE THREAD

**Issue by lovederh** [weexteam/weex-picker#13]
没有报错误，能正常出现选择框，按done后，界面上没有成功显示选择的内容！在iOS11之前是好用的！

**Comment by erha19** [comment]
I will follow this issue.

**Comment by lovederh** [comment]
@erha19 ios中连续调用picker也不好用，在android中是好用的，请一并关注一下吧！

**Comment by zxFlyer** [comment]
@erha19 在iOS 9中调用，点击done的时候会崩溃

**Comment by erha19** [comment]
@zxFlyer You are talking about the performance of the web or native performance？

**Comment by erha19** [comment]
@lovederh @zxFlyer  I can not find your issue on web test, please provide an example for this issue.

This project is only for web, if it is there have some problems on native, you can go to [weex mail list](https://github.com/apache/incubator-weex/blob/master/CONTRIBUTING.md) to create an issue.

**Comment by zxFlyer** [comment]
@erha19 I'm talking about the performance of native.
