### ISSUE TITLE
weex-picker引入说明有错

### ISSUE THREAD

**Issue by hupanfeng** [weexteam/weex-picker#6]
步骤 2

你需要在引入weex-vue-render之后进行模块注册，具体可参考根目录下的./playground/browser/plugininstall.js

目前模块的注册加入了源码中，请保证在weex环境加载之后引入

  <script src="../../../node_modules/vue/dist/vue.runtime.js"></script>
  <script src="../../../node_modules/weex-vue-render/dist/index.js"></script>
  <script src="../../../node_modules/@weex-project/weex-picker/build/index.js"></script>--这里有错，正确的是<script src="../../../node_modules/@weex-project/weex-picker/js/build/index.js"></script>

**Comment by erha19** [comment]
Thanks for your feedback that has been fixed！
